import '../../models/player.dart';

/// Mock list of browsable players, used on the "Find Players" screen
/// so a team captain can invite people to their roster.
/// Replace this with a real backend/API call later.
List<Player> allPlayers = [
  Player(
    name: "ShadowStrike99",
    email: "shadowstrike99@gmail.com",
    uid: "512038471",
    rank: "Grandmaster",
    team: "-",
    country: "India",
    bio: "Aggressive rusher, main entry fragger.",
    level: 65,
    matches: 410,
    wins: 210,
    kills: 1320,
    headshots: 780,
    kd: 3.9,
    tournamentWins: 12,
    mvp: 40,
    totalDamage: 198000,
    favoriteWeapon: "AK47",
    favoriteMap: "Purgatory",
    favoriteMode: "Squad",
    guild: "Nova Esports",
    achievements: ["🏆 Grandmaster", "🔥 Rush King"],
    profileImage: "assets/images/download.jpeg",
  ),
  Player(
    name: "SilentSniper",
    email: "silentsniper@gmail.com",
    uid: "884210937",
    rank: "Heroic",
    team: "-",
    country: "India",
    bio: "Long-range specialist, calm under pressure.",
    level: 58,
    matches: 350,
    wins: 190,
    kills: 980,
    headshots: 640,
    kd: 4.1,
    tournamentWins: 9,
    mvp: 33,
    totalDamage: 152000,
    favoriteWeapon: "Kar98k",
    favoriteMap: "Bermuda",
    favoriteMode: "Battle Royale",
    guild: "Total Gaming",
    achievements: ["🎯 Headshot Master"],
    profileImage: "assets/images/download.jpeg",
  ),
  Player(
    name: "IGL_Kabir",
    email: "kabir.igl@gmail.com",
    uid: "639201845",
    rank: "Master",
    team: "-",
    country: "India",
    bio: "In-game leader, calls rotations and strategy.",
    level: 70,
    matches: 500,
    wins: 260,
    kills: 900,
    headshots: 420,
    kd: 3.2,
    tournamentWins: 18,
    mvp: 25,
    totalDamage: 175000,
    favoriteWeapon: "M4A1",
    favoriteMap: "Kalahari",
    favoriteMode: "Clash Squad",
    guild: "Elite Squad",
    achievements: ["🧠 Best IGL 2025"],
    profileImage: "assets/images/download.jpeg",
  ),
  Player(
    name: "GrenadeQueen",
    email: "grenadequeen@gmail.com",
    uid: "775102938",
    rank: "Elite",
    team: "-",
    country: "India",
    bio: "Grenadier who clears rooms before anyone pushes in.",
    level: 47,
    matches: 280,
    wins: 130,
    kills: 620,
    headshots: 310,
    kd: 2.8,
    tournamentWins: 6,
    mvp: 14,
    totalDamage: 98000,
    favoriteWeapon: "MP40",
    favoriteMap: "Alpine",
    favoriteMode: "Squad",
    guild: "Free Fighters",
    achievements: ["💣 Grenade Specialist"],
    profileImage: "assets/images/download.jpeg",
  ),
];