// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJGid9FlbUcfn5kDppQyD0L6_rdFnzGBM',
    appId: '1:340849569885:web:3ab99166b17190a7fb9db4',
    messagingSenderId: '340849569885',
    projectId: 'esportplay-b5a0f',
    authDomain: 'esportplay-b5a0f.firebaseapp.com',
    storageBucket: 'esportplay-b5a0f.firebasestorage.app',
    measurementId: 'G-SD3FHRNEV1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMTS7wl5aLcGENQUqU4upsp5W02C2GohM',
    appId: '1:340849569885:android:6e2b7f1ee791656ffb9db4',
    messagingSenderId: '340849569885',
    projectId: 'esportplay-b5a0f',
    storageBucket: 'esportplay-b5a0f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWmcaV_P4YnNUHv1bAUQJtJr2rpLpAthU',
    appId: '1:340849569885:ios:5125826b47d33887fb9db4',
    messagingSenderId: '340849569885',
    projectId: 'esportplay-b5a0f',
    storageBucket: 'esportplay-b5a0f.firebasestorage.app',
    iosClientId: '340849569885-ekpojjs53g8d224g882s8u2q5me259od.apps.googleusercontent.com',
    iosBundleId: 'com.example.eposrtplay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWmcaV_P4YnNUHv1bAUQJtJr2rpLpAthU',
    appId: '1:340849569885:ios:5125826b47d33887fb9db4',
    messagingSenderId: '340849569885',
    projectId: 'esportplay-b5a0f',
    storageBucket: 'esportplay-b5a0f.firebasestorage.app',
    iosClientId: '340849569885-ekpojjs53g8d224g882s8u2q5me259od.apps.googleusercontent.com',
    iosBundleId: 'com.example.eposrtplay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJGid9FlbUcfn5kDppQyD0L6_rdFnzGBM',
    appId: '1:340849569885:web:5a2a3d35c70575d9fb9db4',
    messagingSenderId: '340849569885',
    projectId: 'esportplay-b5a0f',
    authDomain: 'esportplay-b5a0f.firebaseapp.com',
    storageBucket: 'esportplay-b5a0f.firebasestorage.app',
    measurementId: 'G-VQZMWEXWR9',
  );
}
